Fix deprecated Sphinx warning API, use logging
Related to issue #8. With Sphinx 1.6 the old sphinx.env.warn() API
was declared as deprecated and will be removed until next minor and
major releases. Instead all Sphinx extensions have to change to the
new Sphinx logging API, see:

    https://www.sphinx-doc.org/pt_BR/1.6/extdev/logging.html

error was:

    TypeError: 'NoneType' object is not callable

similar, see:

    https://github.com/sphinx-doc/sphinx-testing/commit/5e09ddb

Signed-off-by: Stephan Linz <linz@li-pro.net>